Refactor qemu/runvm

diff --git a/qemu/runvm b/qemu/runvm
--- a/qemu/runvm
+++ b/qemu/runvm
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+function fatal() {
+	echo "$@" 1>&2
+	exit 1
+}
+
+function log() {
+	echo "$@" 1>&2
+}
+
 #
 # Default VM opts
 #
@@ -73,8 +82,7 @@ if [ "$host_arch" = "$vm_arch" ] ; then
 			;;
 		*)
 			if [ "$emulated" != "yes" ] ; then
-				echo "Unsupported host OS, use emulated=yes" 1>&2
-				exit 1
+				fatal "Unsupported host OS, use emulated=yes"
 			else
 				accel=""
 			fi
@@ -90,7 +98,7 @@ x86_64)
 	[ "$vnc_video" = "" ] && vnc_video="VGA"
 	;;
 aarch64)
-	if [ "$host_os" = "Darwin" -a "$host_arch" = "aarch64" -a "$vm_arch" = "aarch64" -a "$emulated" != "yes" ] ; then
+	if [ "$host_os" = "Darwin" -a "$host_arch" = "aarch64" -a "$vm_arch" = "aarch64" ] ; then
 		# aarch64 on macOS for Apple Silicon with HVF has a limitations
 		platform="virt,highmem=off"
 		[ "$cpumodel" = "" ] && vcpumodel="cortex-a72"
@@ -101,8 +109,7 @@ aarch64)
 	[ "$vnc_video" = "" ] && vnc_video="ramfb"
 	;;
 *)
-	echo "Unsupported VM arch: $vm_arch" 1>&2
-	exit 1
+	fatal "Unsupported VM arch: $vm_arch"
 	;;
 esac
 
@@ -117,19 +124,17 @@ if ! which $qemu 2>/dev/null 1>/dev/null ; then
 			fi
 		done
 		if [ "$qemu" = "UNKNOWN" ] ; then
-			echo "Unable to find qemu-system-$vm_arch nor qemu-kvm nor qemu-kvm-ev" 1>&2
-			exit 1
+			fatal "Unable to find qemu-system-$vm_arch nor qemu-kvm nor qemu-kvm-ev"
 		fi
 		redhat_qemu="yes"
 		[ "$gui_video" = "vmware-svga" ] && gui_video="VGA"
 		[ "$vnc_video" = "vmware-svga" ] && vnc_video="VGA"
 	else
-		echo "Unable to find qemu-system-$vm_arch for host $host_arch" 1>&2
-		exit 1
+		fatal "Unable to find qemu-system-$vm_arch for host $host_arch"
 	fi
 fi
 
-echo "Using QEMU binary $qemu"
+log "Using QEMU binary $qemu"
 
 share_files="$(dirname $(which $qemu))/../share"
 
@@ -137,62 +142,78 @@ share_files="$(dirname $(which $qemu))/../share"
 # Handle here /bin location with care
 [ "$share_files" = "/bin/../share" ] && share_files="/usr/share"
 
-arch_efis="$share_files/qemu/edk2-$vm_arch-code.fd"
-
-global_efis="
-	$share_files/qemu-efi/QEMU_EFI.fd
-	$share_files/edk2/ovmf/OVMF_CODE.fd
-	$share_files/qemu/OVMF.fd
-	$share_files/qemu-efi-$vm_arch/QEMU_EFI.fd
-"
-
-if [ "$vm_arch" != "x86_64" -o "$legacy_bios" != "yes" ] ; then
-	for global_efi in $global_efis ; do
-		[ -e "$global_efi" ] && break
-	done
-
-	if [ ! -e "$global_efi" ] ; then
-		for global_efi in $arch_efis ; do
-			[ -e "$global_efi" ] && break
-		done
-	fi
-
-	if [ "$efi" = "" -a ! -e "$global_efi" ] ; then
-		echo "EFI path is not set with efi=... and none of" 1>&2
-		for f in $global_efis $arch_efis ; do
-			echo "   $f" 1>&2
-		done
-		echo "was found" 1>&2
-		exit 1
-	fi
-
-	[ "$efi" = "" ] && efi="$global_efi"
-	efi="$(realpath $efi)"
-	echo "Using EFI file $efi"
-
-	if [ "$redhat_qemu" = "yes" ] ; then
-		efi_opts="-drive if=pflash,format=raw,readonly=on,file=$efi"
-		efi_dir=$(dirname $efi)
-		if [ "$private_efi_vars" = "yes" -o "$efi_vars" != "" ] ; then
-			vars_readonly="off"
-			if [ "$efi_vars" = "" ] ; then
-				efi_vars="$vmconfig-efi"
-			fi
-			if [ ! -f "$efi_vars" ] ; then
-				if ! cp "$efi_dir/OVMF_VARS.fd" "$efi_vars" ; then
-					echo "Failed to initialize EFI vars file $efi_dir/OVMF_VARS.fd => $efi_vars" 1>&2
-					exit 1
-				fi
-			fi
+fw_status="broken"
+if [ "$host_os" = "Linux" ] ; then
+	if [ "$legacy_bios" != "yes" ] ; then
+		if [ "$vm_arch" = "aarch64" ] ; then
+			efi_code="$share_files/edk2/aarch64/QEMU_EFI-pflash.raw"
+			vars_file="$share_files/edk2/aarch64/vars-template-pflash.raw"
+			fw_status=require
+		elif [ "$vm_arch" = "arm" ] ; then
+			efi_code="$share_files/edk2/arm/QEMU_EFI-pflash.raw"
+			vars_file="$share_files/edk2/arm/vars-template-pflash.raw"
+			fw_status=require
+		elif [ "$vm_arch" = "x86_64" -o "$vm_arch" = "i386" ] ; then
+			efi_code="$share_files/edk2/ovmv/OVMF_CODE.fd"
+			vars_file="$share_files/edk2/ovmv/OVMF_VARS.fd"
+			fw_status=require
 		else
-			efi_vars="$efi_dir/OVMF_VARS.fd"
-			vars_readonly="on"
+			fatal "EFI unsupported for $vm_arch on $host_os"
 		fi
-		echo "Using EFI vars file $efi"
-    	efi_opts="-drive if=pflash,format=raw,readonly=$vars_readonly,file=$efi_vars"
 	else
-		efi_opts="-bios $efi"
+		[ "$vm_arch" = "x86_64" ] && fw_status=ignore
+		[ "$vm_arch" = "i386" ] && fw_status=ignore
 	fi
+elif [ "$host_os" = "Darwin" ] ; then
+	if [ "$legacy_bios" != "yes" ] ; then
+		if [ "$vm_arch" = "aarch64" ] ; then
+			efi_code="$share_files/qemu/edk2-aarch64-code.fd"
+			vars_file="$share_files/qemu/edk2-arm-vars.fd"
+			fw_status=require
+		elif [ "$vm_arch" = "arm" ] ; then
+			efi_code="$share_files/qemu/edk2-arm-code.fd"
+			vars_file="$share_files/qemu/edk2-arm-vars.fd"
+			fw_status=require
+		elif [ "$vm_arch" = "x86_64" ] ; then
+			efi_code="$share_files/qemu/edk2-x86_64-code.fd"
+			vars_file="$share_files/qemu/edk2-i386-vars.fd"
+			fw_status=require
+		elif [ "$vm_arch" = "i386" ] ; then
+			efi_code="$share_files/qemu/edk2-i386-code.fd"
+			vars_file="$share_files/qemu/edk2-i386-vars.fd"
+			fw_status=require
+		else
+			fatal "EFI unsupported for $vm_arch on $host_os"
+		fi
+	else
+		[ "$vm_arch" = "x86_64" ] && fw_status=ignore
+		[ "$vm_arch" = "i386" ] && fw_status=ignore
+	fi
+fi
+
+if [ "$fw_status" = "ignore" ] ; then
+	log "No special firmware required"
+elif [ "$fw_status" = "require" ] ; then
+	log "Will use EFI code from $efi_code"
+	efi_opts="-drive if=pflash,format=raw,readonly=on,file=$efi_code"
+	if [ "$private_efi_vars" = "yes" ] ; then
+		vars_readonly=off
+		if [ "$efi_vars" = "" ] ; then
+			efi_vars="$confdir/$vmname-efivars"
+		fi
+		log "Will use EFI vars $efi_vars READ-WRITE"
+		if [ ! -f "$efi_vars" ] ; then
+			cp "$vars_file" "$efi_vars" || fatal "Failed to instantiate private vars form $vars_file to $efi_vars"
+			log "Private vars $efi_vars built from $vars_file"
+		fi
+	else
+		vars_readonly=on
+		efi_vars="$vars_file"
+		log "Will use EFI vars $efi_vars READ-ONLY"
+	fi
+	efi_opts="$efi_opts -drive if=pflash,format=raw,readonly=$vars_readonly,file=$efi_vars"
+else
+	fatal "Unknown firmware setup for $vm_arch on $host_os"
 fi
 
 diskopts=""
@@ -236,7 +257,7 @@ for disk in $storages ; do
 	elif [ "$media" = "cdrom" ] ; then
 		diskopts="$diskopts -drive if=none,id=$disk"
 	else
-		echo "Non-CDROM media requires file ""$disk""_type to be set"
+		fatal "Non-CDROM media requires file ""$disk""_type to be set"
 	fi
 	[ "$format" != "" ] && diskopts="$diskopts,format=$format"
 	[ "$cache" != "" ] && diskopts="$diskopts,cache=$cache"
@@ -265,8 +286,7 @@ for net in $networks ; do
 		v="$net"_bridge
 		bridge_name="${!v}"
 		if [ "$bridge_name" = "" ] ; then
-			echo "Interface '$net' require "$net"_bridge=<bridge_if_name> option"
-			exit 1
+			fatal "Interface '$net' require "$net"_bridge=<bridge_if_name> option"
 		fi
 		netdevtype="bridge"
 		netdevopts="br=$bridge_name"
@@ -287,15 +307,13 @@ for net in $networks ; do
 			netdevopts="isolated=on,uuid="$(uuidgen | tr [A-Z] [a-z])
 		elif [ "$mode" = "vms-only" ] ; then
 			if [ "$netuuid" = "" ] ; then
-				echo "Internal network $net requires "$net"_uuid=<value>"
-				exit 1
+				fatal "Internal network $net requires "$net"_uuid=<value>"
 			fi
 			netdevtype="vmnet-host"
 			netdevopts="uuid=$netuud"
 		elif [ "$mode" = "host-only" -o "$mode" = "nat" ] ; then
 			if [ "$ip_start" = "" -o "$ip_end" = "" -o "$ip_mask" = "" ] ; then
-				echo "Interface '$net' require "$net"_ip_start, "$net"_ip_end and "$net"_ip_mask options"
-				exit 1
+				fatal "Interface '$net' require "$net"_ip_start, "$net"_ip_end and "$net"_ip_mask options"
 			fi
 			netdevtype="vmnet-host"
 			[ "$mode" = "nat" ] && netdevtype="vmnet-shared"
@@ -304,31 +322,29 @@ for net in $networks ; do
 			v="$net"_backend
 			backend_dev="${!v}"
 			if [ "$backend_dev" = "" ] ; then
-				echo "Interface '$net' requires "$net"_backend=<physical_device>"
-				exit 1
+				fatal "Interface '$net' requires "$net"_backend=<physical_device>"
 			fi
 			netdevtype="vmnet-bridged"
 			netdevopts="ifname=$backend_dev"
 		else
-			echo "Unsupported "$net"_mode=$mode, must be one of nat | private | internal | isolated"
-			exit 1
+			fatal "Unsupported "$net"_mode=$mode, must be one of nat | private | internal | isolated"
 		fi
 	else
-		echo "Unsupported network device type"
-		echo "The only supported are:"
-		echo "   user  => usermode device with host port redirections"
+		log "Unsupported network device type"
+		log "The only supported are:"
+		log "   user  => usermode device with host port redirections"
 		if [ "$hostos" = "linux" ] ; then
-			echo "   host => attach vm net to existing host bridge"
-			echo "              opts: <name>_bridge  => bridge interface to attach"
+			log "   host => attach vm net to existing host bridge"
+			log "              opts: <name>_bridge  => bridge interface to attach"
 		elif [ "$hostos" = "macos" ] ; then
-			echo "   host => attach vm to virtual host interfaces"
-			echo "           opts: <name>_ip_start"
-			echo "                 <name>_ip_end"
-			echo "                 <name>_ip_mask"
-			echo "                 <name>_mode = vm-only | vms-only | host-only | nat | bridge"
-			echo "                 <name>_backend = <physical_device>"
+			log "   host => attach vm to virtual host interfaces"
+			log "           opts: <name>_ip_start"
+			log "                 <name>_ip_end"
+			log "                 <name>_ip_mask"
+			log "                 <name>_mode = vm-only | vms-only | host-only | nat | bridge"
+			log "                 <name>_backend = <physical_device>"
 		fi
-		exit 1
+		fatal "Aborted"
 	fi
 
 	v="$net"_mac
@@ -359,8 +375,7 @@ if [ "$serial_ports" != "" ] ; then
 			v="$sp"_filepath
 			filepath="${!v}"
 			if [ "$filepath" = "" ] ; then
-				echo "Missing $v value"
-				exit 1
+				fatal "Missing $v value"
 			fi
 			serialopts="$serialopts -device virtserialport,bus=vioser0.0,nr=$nr,chardev=charchannel$nr,id=channel$nr,name=quickemu.$portname"
 			serialopts="$serialopts -chardev serial,id=charchannel$nr,path=$sockpath"
@@ -368,8 +383,7 @@ if [ "$serial_ports" != "" ] ; then
 			serialopts="$serialopts -device virtserialport,bus=vioser0.0,nr=$nr,chardev=charchannel$nr,id=channel$nr,name=quickemu.$portname"
 			serialopts="$serialopts -chardev null,id=charchannel$nr"
 		else
-			echo "Invalid serial port backend $v=$portbackend, must be unix-socket|chardev|null"
-			exit 1
+			fatal "Invalid serial port backend $v=$portbackend, must be unix-socket|chardev|null"
 		fi
 		nr=$(expr $nr + 1)
 	done
@@ -401,7 +415,7 @@ else
 fi
 
 if [ "$vnc_screen" != "" ] ; then
-	echo "VNC screen $vnc_screen"
+	log "VNC screen $vnc_screen"
 fi
 
 baseopts="-name guest=$vmname,debug-threads=on"
@@ -418,8 +432,7 @@ fi
 
 if [ ! -d "$runvm_dir" ] ; then
 	if ! mkdir "$runvm_dir" ; then
-		echo "Unable to create directory $runvm_dir"
-		exit 1
+		fatal "Unable to create directory $runvm_dir"
 	fi
 fi
 
